remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: WUSTL CSE FAQ
description: "Washington University in St. Louis Computer Science and Engineering's FAQ"
